# TCL File Generated by Component Editor 18.1
# Sat Dec 15 10:49:00 CST 2018
# DO NOT MODIFY


# 
# digital_tube_controller "Digital Tube Controller" v1.0
# Verdvana 2018.12.15.10:49:00
# Digital Tube Controller
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module digital_tube_controller
# 
set_module_property DESCRIPTION "Digital Tube Controller"
set_module_property NAME digital_tube_controller
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP DE1-SoC
set_module_property AUTHOR Verdvana
set_module_property DISPLAY_NAME "Digital Tube Controller"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL digital_tube_controller
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file digital_tube_avalon_slaver.v VERILOG PATH digital_tube_avalon_slaver.v
add_fileset_file digital_tube_controller.v VERILOG PATH digital_tube_controller.v TOP_LEVEL_FILE
add_fileset_file digital_tube_seg7.v VERILOG PATH digital_tube_seg7.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset_n
# 
add_interface reset_n reset end
set_interface_property reset_n associatedClock clock
set_interface_property reset_n synchronousEdges DEASSERT
set_interface_property reset_n ENABLED true
set_interface_property reset_n EXPORT_OF ""
set_interface_property reset_n PORT_NAME_MAP ""
set_interface_property reset_n CMSIS_SVD_VARIABLES ""
set_interface_property reset_n SVD_ADDRESS_GROUP ""

add_interface_port reset_n rst_n reset_n Input 1


# 
# connection point avalon_mm_slave
# 
add_interface avalon_mm_slave avalon end
set_interface_property avalon_mm_slave addressUnits WORDS
set_interface_property avalon_mm_slave associatedClock clock
set_interface_property avalon_mm_slave associatedReset reset_n
set_interface_property avalon_mm_slave bitsPerSymbol 8
set_interface_property avalon_mm_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_mm_slave burstcountUnits WORDS
set_interface_property avalon_mm_slave explicitAddressSpan 0
set_interface_property avalon_mm_slave holdTime 0
set_interface_property avalon_mm_slave linewrapBursts false
set_interface_property avalon_mm_slave maximumPendingReadTransactions 0
set_interface_property avalon_mm_slave maximumPendingWriteTransactions 0
set_interface_property avalon_mm_slave readLatency 0
set_interface_property avalon_mm_slave readWaitTime 1
set_interface_property avalon_mm_slave setupTime 0
set_interface_property avalon_mm_slave timingUnits Cycles
set_interface_property avalon_mm_slave writeWaitTime 0
set_interface_property avalon_mm_slave ENABLED true
set_interface_property avalon_mm_slave EXPORT_OF ""
set_interface_property avalon_mm_slave PORT_NAME_MAP ""
set_interface_property avalon_mm_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_mm_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_mm_slave chipselect chipselect Input 1
add_interface_port avalon_mm_slave write_n write_n Input 1
add_interface_port avalon_mm_slave address address Input 1
add_interface_port avalon_mm_slave writedata writedata Input 32
add_interface_port avalon_mm_slave readdata readdata Output 32
set_interface_assignment avalon_mm_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_mm_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_mm_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_mm_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point conduit
# 
add_interface conduit conduit end
set_interface_property conduit associatedClock clock
set_interface_property conduit associatedReset reset_n
set_interface_property conduit ENABLED true
set_interface_property conduit EXPORT_OF ""
set_interface_property conduit PORT_NAME_MAP ""
set_interface_property conduit CMSIS_SVD_VARIABLES ""
set_interface_property conduit SVD_ADDRESS_GROUP ""

add_interface_port conduit hex0 export0 Output 7
add_interface_port conduit hex1 export1 Output 7
add_interface_port conduit hex2 export2 Output 7
add_interface_port conduit hex3 export3 Output 7
add_interface_port conduit hex4 export4 Output 7
add_interface_port conduit hex5 export5 Output 7

